name: online_groceries_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  hive_flutter: ^1.1.0
  change_app_package_name: ^1.4.0
  firebase_storage:
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  razorpay_flutter: ^1.4.0
  http: ^1.6.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/
    - assets/png/category/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 800
